name: CI
on: [push, pull_request]
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: docker-compose up -d
      - name: Tests Coverage
        run: docker-compose exec app bash npm run test