name: CI
on: [push, pull_request]
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Tests
        run: echo "teste"
      - name: Tests Coverage
        run: echo "teste coverage"